language: go
go:
    - 1.9
before_install:
    - go get github.com/ICKelin/glog
    - go get github.com/songgao/water
install:
    - go get github.com/ICKelin/gtun/gtun
    - go get github.com/ICKelin/gtun/gtun_srv
before_script:
script:
    - cd $HOME/gopath/src/github.com/ICKelin/gtun/gtun
    - GOOS=linux go build -o gtun
    - cd $HOME/gopath/src/github.com/ICKelin/gtun/gtun_srv
    - GOOS=linux go build -o gtun_srv 

deploy:
  provider: releases
  api_key: "ec95e41f5f77ea2791a102af224c85d701492838"
  file: "$HOME/gopath/src/github.com/ICKelin/gtun/gtun_srv/gtun_srv"
  skip_cleanup: true
  on:
    tags: true
