language: go
go:
    - 1.9
before_install:
    - go get github.com/ICKelin/glog
    - go get github.com/songgao/water
install:
    - go get github.com/ICKelin/gtun
before_script:
script:
    - cd $HOME/gopath/src/github.com/ICKelin
    - GOOS=linux go build -o gtun gtun.go
    - GOOS=linux go build -o gtun_srv gtun_srv.go
